name: Build dylib
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install gcc
        run: |
          sudo apt update
          sudo apt-get remove clang
        shell: bash
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      - name: build
        run: cargo build --release --all-features
      - name: release
        uses: softprops/action-gh-release@v1
        # only do this step when there's a git tag
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/libdeltapack.so
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-win:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      - name: build
        run: cargo build --release --all-features
      - name: release
        uses: softprops/action-gh-release@v1
        # only do this step when there's a git tag
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/deltapack.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-mac:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true
      - name: build
        run: cargo build --release --all-features
      - name: release
        uses: softprops/action-gh-release@v1
        # only do this step when there's a git tag
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/libdeltapack.dylib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
